"""empty message

Revision ID: 77eead14f19
Revises: None
Create Date: 2015-11-29 13:09:05.898518

"""

# revision identifiers, used by Alembic.
revision = '77eead14f19'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_ping',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('hostName', sa.String(), nullable=True),
    sa.Column('fantasyName', sa.String(), nullable=True),
    sa.Column('connectStatus', sa.String(), nullable=True),
    sa.Column('connectTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('table_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host_ping')
    ### end Alembic commands ###
